export const LIST_QUOTES = 'LIST_QUOTES';
export const RETRIEVE_QUOTE = 'RETRIEVE_QUOTE';
export const SEARCH_QUOTES = 'SEARCH_QUOTES';
export const SEARCH_QUOTES_RECEIVED = 'SEARCH_QUOTES_RECEIVED';
export const SEARCH_FAILED = 'SEARCH_FAILED';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
